Hamburguer = float(input("Digite a quantidade de Hamb:"))
CheeseBurguer = float(input("Digite a quantidade de Cheese: "))
Fritas = float(input("Digite a quantidade de fritas: "))
Refri = float(input("Digite a quantidade de refri: "))
Milkshake = float(input("Digite a quantidade de Milk: "))
SomadosProd = (Hamburguer * 3 + CheeseBurguer * 2.50 + Fritas * 2.50 + Refri * 1 + Milkshake * 3)
print(f"O valor sera de: {SomadosProd}")
